request_url: "https://tianqi.aminer.cn/api/v2/completions_130B"

api_key: "your_api_key"
api_secret: "your_api_secret"

# Paths
GSM8K_path: "path to folder containing GSM8K .jsonl files"
CommonsenseQA_path: "path to folder containing CommonsenseQA .jsonl files"
StrategyQA_path: "path to folder containing StrategyQA .json files"
